apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: cli-myapp
spec:
  selector:
     matchLabels:
       run: cli-myapp
  replicas: 1
  template:
    metadata:
      labels:
       run: cli-myapp
    spec:
      containers:
      - env:
        - name: FABRIC_LOGGING_SPEC
          value: DEBUG
        - name: CORE_PEER_ID
          value: cli
        - name: CORE_PEER_ADDRESS
          value: peer0-hbo-myapp:30751
        - name: CORE_PEER_LOCALMSPID
          value: hboMSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hbo-myapp/users/Admin@hbo-myapp/msp
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hbo-myapp/peers/peer0-hbo-myapp/tls/ca.crt
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix-myapp/peers/peer0-netflix-myapp/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix-myapp/peers/peer0-netflix-myapp/tls/server.key
        image: hyperledger/fabric-tools
        name: cli
        resources: {}
        tty: true
        volumeMounts:
        - name: my-pvc-nfs
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode
          subPath: chaincode
        - name: my-pvc-nfs
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
          subPath: crypto-config
        - name: my-pvc-nfs
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
          subPath: scripts
        - name: my-pvc-nfs
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
          subPath: channel-artifacts
        - name: dockersock
          mountPath: /var/run/docker.sock
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      restartPolicy: Always
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
